replicaCount: 1

image:
  repository: openinnovationsos/aurora-proto
  pullPolicy: IfNotPresent
  tag: "latest"

resources:
  requests:
    memory: "4Gi"
    cpu: "2"
  limits:
    memory: "8Gi"
    cpu: "4"

service:
  type: LoadBalancer
  port: 5000

env:
  - name: MODEL_ID
    value: "Qwen/Qwen2.5-7B-Instruct"
  - name: QUANTIZATION
    value: "awq"
  - name: DEVICE
    value: "cuda"

ingress:
  enabled: false
